# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  name: Default  # Use your self-hosted agent pool name

steps:
- script: |
    copy "C:\Users\Kshitija\drop.zip" "$(Build.ArtifactStagingDirectory)\drop.zip"
  displayName: 'Copy drop.zip to staging folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\drop.zip'
    ArtifactName: 'drop'
  displayName: 'Publish drop.zip as artifact'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ServiceConnection_Automatic'  # Replace with your real service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload `
        --account-name kshitijastore2 `
        --container-name mycontainer `
        --name drop.zip `
        --file "$(Build.ArtifactStagingDirectory)\drop.zip" `
        --auth-mode login
  displayName: 'Upload drop.zip to Azure Blob Storage'
