# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  # Self-hosted agent pool

steps:
- script: |
    copy "C:\Users\Kshitija\drop.zip" "$(Build.ArtifactStagingDirectory)\drop.zip"
  displayName: 'Copy drop.zip to staging folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\drop.zip'
    ArtifactName: 'drop'

# Upload to Azure Blob
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ServiceConnection_Automatic'  # Replace with your service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload `
        --account-name kshitijastore1`
        --container-name mycontainer `
        --name drop.zip `
        --file "$(Build.ArtifactStagingDirectory)\drop.zip" `
        --auth-mode login
  displayName: 'Upload to Azure Blob Storage'

