# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  name: Default  # Your agent pool name

variables:
  STORAGE_ACCOUNT_NAME: kshitijastore2          # Your storage account name
  CONTAINER_NAME: mycontainer                   # Your container name where blob is uploaded

steps:
- script: |
    echo "Copying drop.zip to staging folder..."
    copy "C:\Users\Kshitija\drop.zip" "$(Build.ArtifactStagingDirectory)\drop.zip"
  displayName: 'Copy drop.zip to staging folder'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ServiceConnection_Automatic'  # Your service connection name
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload `
        --account-name $(STORAGE_ACCOUNT_NAME) `
        --container-name $(CONTAINER_NAME) `
        --name drop.zip `
        --file "$(Build.ArtifactStagingDirectory)\drop.zip" `
        --auth-mode key `
        --account-key $(STORAGE_ACCOUNT_KEY)
  displayName: 'Upload drop.zip to Azure Blob Storage using Storage Account Key'
