# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  # Self-hosted agent pool

steps:
- script: |
    copy "C:\Users\Kshitija\drop.zip" "$(Build.ArtifactStagingDirectory)\drop.zip"
  displayName: 'Copy drop.zip to staging folder'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\drop.zip'
    ArtifactName: 'drop'
